// Mystery Choice — varied final result library
// 110 hand-written result variations (11 score levels x 10 each), so the
// final screen never shows the same text twice in a row for the same score.
// Selection happens ONCE per completed game (see MysteryChoiceGame.tsx) and
// the chosen result id is saved into the shared session state so both
// players — and a page refresh — always see the identical result.

export interface MysteryResultVariation {
  id: string
  score: number       // 0-10, real match count out of 10
  titleEn: string
  titleGr: string
  descriptionEn: string
  descriptionGr: string
  emoji: string
}

// 110 variations total — 10 per score level (0 through 10)
export const MYSTERY_RESULT_LIBRARY: MysteryResultVariation[] = [
  { id: 'score_0_result_01', score: 0, titleEn: 'Opposites in the Room', titleGr: 'Αντίθετοι στον Χώρο', descriptionEn: 'You two see the world in almost completely different ways — which could make for a genuinely interesting conversation.', descriptionGr: 'Βλέπετε τον κόσμο με σχεδόν εντελώς διαφορετικό τρόπο — κάτι που θα μπορούσε να γίνει μια πραγματικά ενδιαφέρουσα συζήτηση.', emoji: '🌗' },
  { id: 'score_0_result_02', score: 0, titleEn: 'Total Contrast', titleGr: 'Ολική Αντίθεση', descriptionEn: 'Not a single answer lined up — sometimes the most memorable conversations start from total contrast.', descriptionGr: 'Καμία απάντηση δεν ταίριαξε — μερικές φορές οι πιο αξέχαστες συζητήσεις ξεκινούν από την ολική αντίθεση.', emoji: '🎭' },
  { id: 'score_0_result_03', score: 0, titleEn: 'A Blank Canvas', titleGr: 'Ένας Λευκός Καμβάς', descriptionEn: 'You\'re starting from very different places, which means there\'s a lot of genuine discovering left to do.', descriptionGr: 'Ξεκινάτε από πολύ διαφορετικά σημεία, που σημαίνει ότι υπάρχει πολύ γνήσια ανακάλυψη μπροστά σας.', emoji: '🖼️' },
  { id: 'score_0_result_04', score: 0, titleEn: 'Different Wavelengths', titleGr: 'Διαφορετικά Μήκη Κύματος', descriptionEn: 'Right now you\'re tuned to different frequencies — it happens, and it\'s worth staying curious about why.', descriptionGr: 'Αυτή τη στιγμή είστε συντονισμένοι σε διαφορετικές συχνότητες — συμβαίνει, και αξίζει να μείνετε περίεργοι για το γιατί.', emoji: '📻' },
  { id: 'score_0_result_05', score: 0, titleEn: 'A Clean Slate', titleGr: 'Ένα Καθαρό Ξεκίνημα', descriptionEn: 'Zero overlaps this round — that\'s not a verdict, just a starting point for asking better questions.', descriptionGr: 'Μηδέν κοινά αυτόν τον γύρο — αυτό δεν είναι ετυμηγορία, απλά ένα σημείο εκκίνησης για καλύτερες ερωτήσεις.', emoji: '📄' },
  { id: 'score_0_result_06', score: 0, titleEn: 'Uncharted Territory', titleGr: 'Ανεξερεύνητο Έδαφος', descriptionEn: 'You answered very differently across the board — sometimes that\'s exactly where real curiosity begins.', descriptionGr: 'Απαντήσατε πολύ διαφορετικά σε όλα — μερικές φορές ακριβώς εκεί ξεκινά η πραγματική περιέργεια.', emoji: '🧭' },
  { id: 'score_0_result_07', score: 0, titleEn: 'Two Different Stories', titleGr: 'Δύο Διαφορετικές Ιστορίες', descriptionEn: 'Your answers read like two different stories — worth hearing each other out to see where they might meet.', descriptionGr: 'Οι απαντήσεις σας μοιάζουν με δύο διαφορετικές ιστορίες — αξίζει να ακούσετε ο ένας τον άλλον για να δείτε πού μπορεί να συναντηθούν.', emoji: '📚' },
  { id: 'score_0_result_08', score: 0, titleEn: 'Wide Open Questions', titleGr: 'Ανοιχτές Ερωτήσεις', descriptionEn: 'You didn\'t match this time, but that leaves plenty of honest questions to ask each other.', descriptionGr: 'Δεν ταιριάξατε αυτή τη φορά, αλλά αυτό αφήνει πολλές ειλικρινείς ερωτήσεις να κάνετε ο ένας στον άλλον.', emoji: '❓' },
  { id: 'score_0_result_09', score: 0, titleEn: 'A Fresh Perspective', titleGr: 'Μια Φρέσκια Ματιά', descriptionEn: 'Seeing things this differently isn\'t a red flag — it just means you\'d each bring something new to the table.', descriptionGr: 'Το να βλέπετε τα πράγματα τόσο διαφορετικά δεν είναι κακό σημάδι — απλά σημαίνει ότι ο καθένας φέρνει κάτι νέο.', emoji: '🔎' },
  { id: 'score_0_result_10', score: 0, titleEn: 'Starting From Scratch', titleGr: 'Ξεκινώντας Από την Αρχή', descriptionEn: 'No matches this round, but every real connection has to start somewhere — maybe this is that somewhere.', descriptionGr: 'Κανένα ταίριασμα αυτόν τον γύρο, αλλά κάθε αληθινή σύνδεση πρέπει να ξεκινήσει από κάπου — ίσως αυτό είναι το κάπου.', emoji: '🌱' },
  { id: 'score_1_result_01', score: 1, titleEn: 'One Small Spark', titleGr: 'Μια Μικρή Σπίθα', descriptionEn: 'Just one thing lined up — small, but real. Sometimes that\'s all a good conversation needs to start.', descriptionGr: 'Μόνο ένα πράγμα ταίριαξε — μικρό, αλλά αληθινό. Μερικές φορές αυτό αρκεί για να ξεκινήσει μια καλή συζήτηση.', emoji: '✨' },
  { id: 'score_1_result_02', score: 1, titleEn: 'A Single Thread', titleGr: 'Ένα Μονό Νήμα', descriptionEn: 'You\'re quite different overall, but one shared answer gives you something to pull on.', descriptionGr: 'Είστε αρκετά διαφορετικοί συνολικά, αλλά μία κοινή απάντηση σας δίνει κάτι να ανοίξετε.', emoji: '🧵' },
  { id: 'score_1_result_03', score: 1, titleEn: 'Mostly Different, Slightly Curious', titleGr: 'Κυρίως Διαφορετικοί, Λίγο Περίεργοι', descriptionEn: 'One match among many differences — enough to be a little curious about each other.', descriptionGr: 'Ένα ταίριασμα ανάμεσα σε πολλές διαφορές — αρκετό για να είστε λίγο περίεργοι ο ένας για τον άλλον.', emoji: '🤔' },
  { id: 'score_1_result_04', score: 1, titleEn: 'A Rare Overlap', titleGr: 'Μια Σπάνια Επικάλυψη', descriptionEn: 'You approach most things differently, but you found one genuine point in common.', descriptionGr: 'Προσεγγίζετε τα περισσότερα διαφορετικά, αλλά βρήκατε ένα γνήσιο κοινό σημείο.', emoji: '🔹' },
  { id: 'score_1_result_05', score: 1, titleEn: 'Different Paths, One Crossing', titleGr: 'Διαφορετικοί Δρόμοι, Ένα Σταυροδρόμι', descriptionEn: 'Your paths mostly diverge, but they cross in one interesting place.', descriptionGr: 'Οι δρόμοι σας κυρίως αποκλίνουν, αλλά διασταυρώνονται σε ένα ενδιαφέρον σημείο.', emoji: '🛤️' },
  { id: 'score_1_result_06', score: 1, titleEn: 'Almost Opposites', titleGr: 'Σχεδόν Αντίθετοι', descriptionEn: 'You lean in very different directions, with one small exception worth exploring.', descriptionGr: 'Γέρνετε προς πολύ διαφορετικές κατευθύνσεις, με μία μικρή εξαίρεση που αξίζει να εξερευνήσετε.', emoji: '↔️' },
  { id: 'score_1_result_07', score: 1, titleEn: 'One Thing in Common', titleGr: 'Ένα Κοινό Πράγμα', descriptionEn: 'Out of everything, one answer matched — worth asking what made that one click.', descriptionGr: 'Από όλα, μία απάντηση ταίριαξε — αξίζει να ρωτήσετε τι έκανε αυτή να κλικάρει.', emoji: '🎯' },
  { id: 'score_1_result_08', score: 1, titleEn: 'A Quiet Connection Point', titleGr: 'Ένα Ήσυχο Σημείο Σύνδεσης', descriptionEn: 'Mostly different personalities, but one quiet point where you actually agree.', descriptionGr: 'Κυρίως διαφορετικές προσωπικότητες, αλλά ένα ήσυχο σημείο όπου πραγματικά συμφωνείτε.', emoji: '🕯️' },
  { id: 'score_1_result_09', score: 1, titleEn: 'Contrast With a Twist', titleGr: 'Αντίθεση με μια Ανατροπή', descriptionEn: 'You contrast on almost everything except one small, telling detail.', descriptionGr: 'Έχετε αντίθεση σε σχεδόν όλα εκτός από μία μικρή, αποκαλυπτική λεπτομέρεια.', emoji: '🌀' },
  { id: 'score_1_result_10', score: 1, titleEn: 'A Different Duo', titleGr: 'Ένα Διαφορετικό Δίδυμο', descriptionEn: 'Different in most ways, but that one shared answer is worth a conversation of its own.', descriptionGr: 'Διαφορετικοί στα περισσότερα, αλλά αυτή η μία κοινή απάντηση αξίζει τη δική της συζήτηση.', emoji: '🎈' },
  { id: 'score_2_result_01', score: 2, titleEn: 'A Couple of Clues', titleGr: 'Μερικά Στοιχεία', descriptionEn: 'A couple of answers lined up — enough small clues to build a real conversation on.', descriptionGr: 'Μερικές απαντήσεις ταίριαξαν — αρκετά μικρά στοιχεία για να χτίσετε μια πραγματική συζήτηση.', emoji: '🔍' },
  { id: 'score_2_result_02', score: 2, titleEn: 'Two Points of Agreement', titleGr: 'Δύο Σημεία Συμφωνίας', descriptionEn: 'You mostly differ, but found two genuine points of agreement worth talking through.', descriptionGr: 'Κυρίως διαφέρετε, αλλά βρήκατε δύο γνήσια σημεία συμφωνίας που αξίζει να συζητήσετε.', emoji: '🤝' },
  { id: 'score_2_result_03', score: 2, titleEn: 'Small But Real', titleGr: 'Μικρό αλλά Αληθινό', descriptionEn: 'The overlap is small, but it\'s real — a decent starting point for getting to know each other.', descriptionGr: 'Η επικάλυψη είναι μικρή, αλλά είναι αληθινή — ένα καλό σημείο εκκίνησης για να γνωριστείτε.', emoji: '💫' },
  { id: 'score_2_result_04', score: 2, titleEn: 'Different, With Exceptions', titleGr: 'Διαφορετικοί, με Εξαιρέσεις', descriptionEn: 'You differ in most areas, but a couple of exceptions stand out and could be worth exploring.', descriptionGr: 'Διαφέρετε στα περισσότερα, αλλά μερικές εξαιρέσεις ξεχωρίζουν και αξίζει να τις εξερευνήσετε.', emoji: '🌟' },
  { id: 'score_2_result_05', score: 2, titleEn: 'Unexpected Common Ground', titleGr: 'Απροσδόκητο Κοινό Έδαφος', descriptionEn: 'Given how differently you see most things, these two matches feel like a pleasant surprise.', descriptionGr: 'Δεδομένου του πόσο διαφορετικά βλέπετε τα περισσότερα, αυτά τα δύο ταιριάσματα είναι μια ευχάριστη έκπληξη.', emoji: '🎁' },
  { id: 'score_2_result_06', score: 2, titleEn: 'Room to Grow', titleGr: 'Χώρος για Ανάπτυξη', descriptionEn: 'There\'s not much overlap yet, but what\'s there feels genuine and worth building on.', descriptionGr: 'Δεν υπάρχει πολλή επικάλυψη ακόμα, αλλά αυτό που υπάρχει φαίνεται γνήσιο και αξίζει να χτιστεί πάνω του.', emoji: '🌿' },
  { id: 'score_2_result_07', score: 2, titleEn: 'Two Shared Signals', titleGr: 'Δύο Κοινά Σήματα', descriptionEn: 'Two signals came through clearly amid the differences — worth following up on both.', descriptionGr: 'Δύο σήματα ήρθαν καθαρά μέσα από τις διαφορές — αξίζει να ακολουθήσετε και τα δύο.', emoji: '📶' },
  { id: 'score_2_result_08', score: 2, titleEn: 'A Small Bridge', titleGr: 'Μια Μικρή Γέφυρα', descriptionEn: 'You\'re on different sides of most things, but a small bridge connects a couple of them.', descriptionGr: 'Είστε σε διαφορετικές πλευρές στα περισσότερα, αλλά μια μικρή γέφυρα συνδέει μερικά από αυτά.', emoji: '🌉' },
  { id: 'score_2_result_09', score: 2, titleEn: 'Worth a Second Look', titleGr: 'Αξίζει Δεύτερη Ματιά', descriptionEn: 'Not much matched, but what did feels worth a second, closer look.', descriptionGr: 'Δεν ταίριαξαν πολλά, αλλά αυτά που ταίριαξαν αξίζουν μια δεύτερη, πιο προσεκτική ματιά.', emoji: '🔭' },
  { id: 'score_2_result_10', score: 2, titleEn: 'Two Sparks in the Dark', titleGr: 'Δύο Σπίθες στο Σκοτάδι', descriptionEn: 'Amid a lot of contrast, two genuine sparks stood out clearly.', descriptionGr: 'Μέσα σε πολλή αντίθεση, δύο γνήσιες σπίθες ξεχώρισαν καθαρά.', emoji: '🕯️' },
  { id: 'score_3_result_01', score: 3, titleEn: 'A Few Shared Notes', titleGr: 'Μερικές Κοινές Νότες', descriptionEn: 'Your styles differ overall, but a few shared preferences give you real material to talk about.', descriptionGr: 'Τα στιλ σας διαφέρουν συνολικά, αλλά μερικές κοινές προτιμήσεις σας δίνουν πραγματικό υλικό για συζήτηση.', emoji: '🎵' },
  { id: 'score_3_result_02', score: 3, titleEn: 'Different Styles, Real Overlap', titleGr: 'Διαφορετικά Στιλ, Πραγματική Επικάλυψη', descriptionEn: 'You approach life differently, but three real preferences line up along the way.', descriptionGr: 'Προσεγγίζετε τη ζωή διαφορετικά, αλλά τρεις πραγματικές προτιμήσεις ταιριάζουν στην πορεία.', emoji: '🧩' },
  { id: 'score_3_result_03', score: 3, titleEn: 'A Handful in Common', titleGr: 'Μια Χούφτα Κοινά', descriptionEn: 'You found a handful of things you agree on — enough to build a genuine first conversation.', descriptionGr: 'Βρήκατε μια χούφτα πράγματα που συμφωνείτε — αρκετά για μια γνήσια πρώτη συζήτηση.', emoji: '🤲' },
  { id: 'score_3_result_04', score: 3, titleEn: 'Different Roads, Shared Stops', titleGr: 'Διαφορετικοί Δρόμοι, Κοινές Στάσεις', descriptionEn: 'Your journeys look different, but you stop at a few of the same places along the way.', descriptionGr: 'Τα ταξίδια σας φαίνονται διαφορετικά, αλλά σταματάτε σε μερικά ίδια σημεία στην πορεία.', emoji: '🚏' },
  { id: 'score_3_result_05', score: 3, titleEn: 'Contrast With Character', titleGr: 'Αντίθεση με Χαρακτήρα', descriptionEn: 'You\'re quite different people, and a few genuine matches give that contrast some real texture.', descriptionGr: 'Είστε αρκετά διαφορετικοί άνθρωποι, και μερικά γνήσια ταιριάσματα δίνουν σε αυτή την αντίθεση υφή.', emoji: '🎨' },
  { id: 'score_3_result_06', score: 3, titleEn: 'Enough to Start', titleGr: 'Αρκετό για να Ξεκινήσετε', descriptionEn: 'It\'s not a big overlap, but it\'s enough of a foundation to genuinely start getting to know each other.', descriptionGr: 'Δεν είναι μεγάλη επικάλυψη, αλλά είναι αρκετό θεμέλιο για να αρχίσετε πραγματικά να γνωρίζεστε.', emoji: '🏗️' },
  { id: 'score_3_result_07', score: 3, titleEn: 'A Few Genuine Matches', titleGr: 'Μερικά Γνήσια Ταιριάσματα', descriptionEn: 'Out of ten, three answers genuinely lined up — a real, modest starting point.', descriptionGr: 'Από τα δέκα, τρεις απαντήσεις ταίριαξαν πραγματικά — ένα αληθινό, μέτριο σημείο εκκίνησης.', emoji: '✅' },
  { id: 'score_3_result_08', score: 3, titleEn: 'Different Beat, Shared Rhythm', titleGr: 'Διαφορετικό Ρυθμό, Κοινό Beat', descriptionEn: 'You move to different beats most of the time, but occasionally you land on the same rhythm.', descriptionGr: 'Κινείστε σε διαφορετικούς ρυθμούς τις περισσότερες φορές, αλλά κάπου κάπου πέφτετε στον ίδιο ρυθμό.', emoji: '🥁' },
  { id: 'score_3_result_09', score: 3, titleEn: 'A Modest Overlap', titleGr: 'Μια Μέτρια Επικάλυψη', descriptionEn: 'Your preferences overlap modestly — small, but a genuine place to keep exploring from.', descriptionGr: 'Οι προτιμήσεις σας επικαλύπτονται μέτρια — μικρό, αλλά ένα γνήσιο σημείο για να συνεχίσετε να εξερευνάτε.', emoji: '📊' },
  { id: 'score_3_result_10', score: 3, titleEn: 'A Few Things Worth Noting', titleGr: 'Μερικά Πράγματα Αξιοσημείωτα', descriptionEn: 'Mostly different, but a few answers stood out as genuinely worth noting.', descriptionGr: 'Κυρίως διαφορετικοί, αλλά μερικές απαντήσεις ξεχώρισαν ως πραγματικά αξιοσημείωτες.', emoji: '📝' },
  { id: 'score_4_result_01', score: 4, titleEn: 'A Real Starting Point', titleGr: 'Ένα Πραγματικό Σημείο Εκκίνησης', descriptionEn: 'You share some real common ground, with plenty still left to discover about each other.', descriptionGr: 'Μοιράζεστε κάποιο πραγματικό κοινό έδαφος, με πολλά ακόμα να ανακαλύψετε ο ένας για τον άλλον.', emoji: '🌤️' },
  { id: 'score_4_result_02', score: 4, titleEn: 'Some Pieces Fit', titleGr: 'Μερικά Κομμάτια Ταιριάζουν', descriptionEn: 'A good number of pieces already fit together — the rest of the puzzle is still an open, exciting question.', descriptionGr: 'Αρκετά κομμάτια ήδη ταιριάζουν — το υπόλοιπο παζλ είναι ακόμα μια ανοιχτή, συναρπαστική ερώτηση.', emoji: '🧩' },
  { id: 'score_4_result_03', score: 4, titleEn: 'Early Signs of Connection', titleGr: 'Πρώιμα Σημάδια Σύνδεσης', descriptionEn: 'There\'s a genuine early connection here, and enough differences to keep things interesting.', descriptionGr: 'Υπάρχει μια γνήσια πρώιμη σύνδεση εδώ, και αρκετές διαφορές για να παραμείνουν τα πράγματα ενδιαφέροντα.', emoji: '🌱' },
  { id: 'score_4_result_04', score: 4, titleEn: 'A Solid Foundation', titleGr: 'Μια Σταθερή Βάση', descriptionEn: 'You\'ve built a solid enough foundation to keep discovering more about each other from here.', descriptionGr: 'Έχετε χτίσει μια αρκετά σταθερή βάση για να συνεχίσετε να ανακαλύπτετε περισσότερα ο ένας για τον άλλον.', emoji: '🧱' },
  { id: 'score_4_result_05', score: 4, titleEn: 'Worth Getting to Know', titleGr: 'Αξίζει να Γνωριστείτε', descriptionEn: 'You match on some real things, and the differences leave genuine ground to explore together.', descriptionGr: 'Ταιριάζετε σε κάποια πραγματικά πράγματα, και οι διαφορές αφήνουν γνήσιο έδαφος να εξερευνήσετε μαζί.', emoji: '🔦' },
  { id: 'score_4_result_06', score: 4, titleEn: 'A Promising Mix', titleGr: 'Ένα Υποσχόμενο Μείγμα', descriptionEn: 'A promising mix of shared ground and open questions — the kind that makes for good conversation.', descriptionGr: 'Ένα υποσχόμενο μείγμα κοινού εδάφους και ανοιχτών ερωτήσεων — το είδος που κάνει καλή συζήτηση.', emoji: '🌈' },
  { id: 'score_4_result_07', score: 4, titleEn: 'Some Real Overlap', titleGr: 'Κάποια Πραγματική Επικάλυψη', descriptionEn: 'You genuinely overlap on a few important things — a fair place to build from.', descriptionGr: 'Επικαλύπτεστε πραγματικά σε μερικά σημαντικά πράγματα — ένα δίκαιο σημείο για να χτίσετε πάνω του.', emoji: '🔗' },
  { id: 'score_4_result_08', score: 4, titleEn: 'Getting Somewhere', titleGr: 'Πάτε Κάπου', descriptionEn: 'You\'re getting somewhere real — not everything lines up yet, but enough does to matter.', descriptionGr: 'Πηγαίνετε κάπου πραγματικό — δεν ταιριάζουν ακόμα όλα, αλλά αρκετά ταιριάζουν ώστε να έχει σημασία.', emoji: '🚶' },
  { id: 'score_4_result_09', score: 4, titleEn: 'Enough to Be Curious', titleGr: 'Αρκετό για να Είσαι Περίεργος', descriptionEn: 'You share enough that being curious about each other feels natural.', descriptionGr: 'Μοιράζεστε αρκετά ώστε να είναι φυσικό να είστε περίεργοι ο ένας για τον άλλον.', emoji: '💡' },
  { id: 'score_4_result_10', score: 4, titleEn: 'A Fair Match', titleGr: 'Ένα Δίκαιο Ταίριασμα', descriptionEn: 'A fair number of things line up — not everything, but a genuine, honest connection to start from.', descriptionGr: 'Αρκετά πράγματα ταιριάζουν — όχι όλα, αλλά μια γνήσια, ειλικρινής σύνδεση για να ξεκινήσετε.', emoji: '⚖️' },
  { id: 'score_5_result_01', score: 5, titleEn: 'Perfectly Balanced', titleGr: 'Τέλεια Ισορροπημένοι', descriptionEn: 'An even split between what you share and where you differ — a genuinely balanced connection.', descriptionGr: 'Ένας ισότιμος συνδυασμός ανάμεσα σε αυτά που μοιράζεστε και σε αυτά που διαφέρετε — μια πραγματικά ισορροπημένη σύνδεση.', emoji: '⚖️' },
  { id: 'score_5_result_02', score: 5, titleEn: 'Half and Half', titleGr: 'Μισά-Μισά', descriptionEn: 'Right down the middle — enough in common to connect, enough different to keep it interesting.', descriptionGr: 'Ακριβώς στη μέση — αρκετά κοινά για να συνδεθείτε, αρκετές διαφορές για να μείνει ενδιαφέρον.', emoji: '🌗' },
  { id: 'score_5_result_03', score: 5, titleEn: 'An Even Match', titleGr: 'Ένα Ισότιμο Ταίριασμα', descriptionEn: 'You match on half of what matters and differ on the rest — a genuinely even foundation.', descriptionGr: 'Ταιριάζετε στα μισά από όσα έχουν σημασία και διαφέρετε στα υπόλοιπα — μια γνήσια ισότιμη βάση.', emoji: '🎯' },
  { id: 'score_5_result_04', score: 5, titleEn: 'Balance in Motion', titleGr: 'Ισορροπία σε Κίνηση', descriptionEn: 'A healthy balance of common ground and contrast — the kind that keeps a connection interesting.', descriptionGr: 'Μια υγιής ισορροπία κοινού εδάφους και αντίθεσης — αυτή που κρατά μια σύνδεση ενδιαφέρουσα.', emoji: '🌀' },
  { id: 'score_5_result_05', score: 5, titleEn: 'Equal Parts Familiar and New', titleGr: 'Ίσα Μέρη Γνώριμο και Νέο', descriptionEn: 'Half of this feels familiar, half feels new — a genuinely interesting place to be.', descriptionGr: 'Τα μισά μοιάζουν γνώριμα, τα μισά μοιάζουν νέα — ένα πραγματικά ενδιαφέρον σημείο.', emoji: '🔄' },
  { id: 'score_5_result_06', score: 5, titleEn: 'A Middle Ground', titleGr: 'Ένα Μέσο Έδαφος', descriptionEn: 'You\'ve landed on genuine middle ground — real similarities, real differences, both worth exploring.', descriptionGr: 'Έχετε καταλήξει σε γνήσιο μέσο έδαφος — πραγματικές ομοιότητες, πραγματικές διαφορές, και τα δύο αξίζει να εξερευνηθούν.', emoji: '🏞️' },
  { id: 'score_5_result_07', score: 5, titleEn: 'Fifty-Fifty Chemistry', titleGr: 'Χημεία Πενήντα-Πενήντα', descriptionEn: 'An even split of chemistry and contrast — a solid, honest place to start from.', descriptionGr: 'Ένας ισότιμος συνδυασμός χημείας και αντίθεσης — ένα στέρεο, ειλικρινές σημείο εκκίνησης.', emoji: '🧪' },
  { id: 'score_5_result_08', score: 5, titleEn: 'Two Sides, One Story', titleGr: 'Δύο Πλευρές, Μία Ιστορία', descriptionEn: 'You bring two distinct sides to the table, but together they form one balanced story.', descriptionGr: 'Φέρνετε δύο ξεχωριστές πλευρές, αλλά μαζί σχηματίζουν μία ισορροπημένη ιστορία.', emoji: '📖' },
  { id: 'score_5_result_09', score: 5, titleEn: 'A Genuine Middle', titleGr: 'Ένα Γνήσιο Μέσο', descriptionEn: 'Right in the genuine middle — not overwhelming similarity, not stark contrast, just balance.', descriptionGr: 'Ακριβώς στη γνήσια μέση — ούτε συντριπτική ομοιότητα, ούτε έντονη αντίθεση, απλά ισορροπία.', emoji: '🎚️' },
  { id: 'score_5_result_10', score: 5, titleEn: 'Steady Ground', titleGr: 'Σταθερό Έδαφος', descriptionEn: 'You stand on steady, balanced ground — half shared, half yours to discover together.', descriptionGr: 'Στέκεστε σε σταθερό, ισορροπημένο έδαφος — μισό κοινό, μισό δικό σας να ανακαλύψετε μαζί.', emoji: '🪨' },
  { id: 'score_6_result_01', score: 6, titleEn: 'A Promising Sign', titleGr: 'Ένα Υποσχόμενο Σημάδι', descriptionEn: 'More than half of your answers lined up — a genuinely promising sign for a first connection.', descriptionGr: 'Πάνω από τις μισές απαντήσεις σας ταίριαξαν — ένα πραγματικά υποσχόμενο σημάδι για μια πρώτη σύνδεση.', emoji: '🌅' },
  { id: 'score_6_result_02', score: 6, titleEn: 'Meaningful Common Ground', titleGr: 'Ουσιαστικό Κοινό Έδαφος', descriptionEn: 'You\'ve found meaningful common ground on more than half of what you were asked.', descriptionGr: 'Έχετε βρει ουσιαστικό κοινό έδαφος σε πάνω από τα μισά από όσα σας ρωτήθηκαν.', emoji: '🌍' },
  { id: 'score_6_result_03', score: 6, titleEn: 'Good Chemistry Forming', titleGr: 'Καλή Χημεία Δημιουργείται', descriptionEn: 'There\'s real chemistry starting to form here, built on solid, genuine overlap.', descriptionGr: 'Υπάρχει πραγματική χημεία που αρχίζει να σχηματίζεται εδώ, χτισμένη σε στέρεη, γνήσια επικάλυψη.', emoji: '⚗️' },
  { id: 'score_6_result_04', score: 6, titleEn: 'More Alike Than Not', titleGr: 'Πιο Όμοιοι Παρά Όχι', descriptionEn: 'You\'re more alike than different — a strong, promising base to build a connection on.', descriptionGr: 'Είστε πιο όμοιοι παρά διαφορετικοί — μια δυνατή, υποσχόμενη βάση για να χτίσετε μια σύνδεση.', emoji: '🤍' },
  { id: 'score_6_result_05', score: 6, titleEn: 'A Solid Six', titleGr: 'Ένα Στέρεο Έξι', descriptionEn: 'Six real matches out of ten — solid, genuine, and worth building on.', descriptionGr: 'Έξι πραγματικά ταιριάσματα στα δέκα — στέρεα, γνήσια, και αξίζει να χτιστούν πάνω τους.', emoji: '🎲' },
  { id: 'score_6_result_06', score: 6, titleEn: 'Genuinely Compatible Ground', titleGr: 'Γνήσια Συμβατό Έδαφος', descriptionEn: 'You share genuinely compatible ground on the majority of what you were asked.', descriptionGr: 'Μοιράζεστε γνήσια συμβατό έδαφος στην πλειοψηφία από όσα σας ρωτήθηκαν.', emoji: '🧭' },
  { id: 'score_6_result_07', score: 6, titleEn: 'A Warm Start', titleGr: 'Μια Ζεστή Αρχή', descriptionEn: 'This feels like a warm, promising start — more common ground than not.', descriptionGr: 'Αυτό μοιάζει με μια ζεστή, υποσχόμενη αρχή — περισσότερο κοινό έδαφος παρά όχι.', emoji: '☀️' },
  { id: 'score_6_result_08', score: 6, titleEn: 'Building Real Trust', titleGr: 'Χτίζοντας Πραγματική Εμπιστοσύνη', descriptionEn: 'You\'ve matched on enough real things to start building genuine trust from here.', descriptionGr: 'Έχετε ταιριάξει σε αρκετά πραγματικά πράγματα για να αρχίσετε να χτίζετε γνήσια εμπιστοσύνη από εδώ.', emoji: '🔐' },
  { id: 'score_6_result_09', score: 6, titleEn: 'More Than Halfway There', titleGr: 'Πάνω από τη Μέση Διαδρομή', descriptionEn: 'You\'re more than halfway aligned — a genuinely encouraging place to be.', descriptionGr: 'Είστε πάνω από τη μέση διαδρομή ευθυγράμμισης — ένα πραγματικά ενθαρρυντικό σημείο.', emoji: '🛣️' },
  { id: 'score_6_result_10', score: 6, titleEn: 'A Encouraging Overlap', titleGr: 'Μια Ενθαρρυντική Επικάλυψη', descriptionEn: 'The overlap here is genuinely encouraging, without being overstated.', descriptionGr: 'Η επικάλυψη εδώ είναι πραγματικά ενθαρρυντική, χωρίς να είναι υπερβολική.', emoji: '📈' },
  { id: 'score_7_result_01', score: 7, titleEn: 'A Real Spark', titleGr: 'Υπάρχει Πραγματική Σπίθα', descriptionEn: 'You share several meaningful preferences, while your differences leave plenty to discover.', descriptionGr: 'Μοιράζεστε αρκετές ουσιαστικές προτιμήσεις, ενώ οι διαφορές σας αφήνουν πολλά ακόμη να ανακαλύψετε.', emoji: '✨' },
  { id: 'score_7_result_02', score: 7, titleEn: 'Strong Potential', titleGr: 'Δυνατή Δυναμική', descriptionEn: 'Seven genuine matches out of ten — this has real, strong potential worth exploring further.', descriptionGr: 'Επτά γνήσια ταιριάσματα στα δέκα — αυτό έχει πραγματική, δυνατή δυναμική που αξίζει να εξερευνηθεί.', emoji: '🚀' },
  { id: 'score_7_result_03', score: 7, titleEn: 'Several Important Matches', titleGr: 'Αρκετά Σημαντικά Ταιριάσματα', descriptionEn: 'You align on several genuinely important things — a strong signal worth paying attention to.', descriptionGr: 'Ευθυγραμμίζεστε σε αρκετά πραγματικά σημαντικά πράγματα — ένα δυνατό σήμα που αξίζει προσοχή.', emoji: '📡' },
  { id: 'score_7_result_04', score: 7, titleEn: 'A Strong Foundation', titleGr: 'Μια Δυνατή Βάση', descriptionEn: 'You\'ve built a genuinely strong foundation of shared answers to keep growing from.', descriptionGr: 'Έχετε χτίσει μια πραγματικά δυνατή βάση κοινών απαντήσεων για να συνεχίσετε να αναπτύσσεστε.', emoji: '🏛️' },
  { id: 'score_7_result_05', score: 7, titleEn: 'Real Momentum', titleGr: 'Πραγματική Ορμή', descriptionEn: 'There\'s genuine momentum here — more agreement than not, and it shows.', descriptionGr: 'Υπάρχει γνήσια ορμή εδώ — περισσότερη συμφωνία παρά όχι, και φαίνεται.', emoji: '🌊' },
  { id: 'score_7_result_06', score: 7, titleEn: 'A Compatible Rhythm', titleGr: 'Ένας Συμβατός Ρυθμός', descriptionEn: 'You move in a genuinely compatible rhythm on most of what matters.', descriptionGr: 'Κινείστε σε έναν πραγματικά συμβατό ρυθμό στα περισσότερα από όσα έχουν σημασία.', emoji: '🎼' },
  { id: 'score_7_result_07', score: 7, titleEn: 'Well Aligned', titleGr: 'Καλά Ευθυγραμμισμένοι', descriptionEn: 'You\'re well aligned on the things that count, with just enough difference to stay interesting.', descriptionGr: 'Είστε καλά ευθυγραμμισμένοι σε όσα μετράνε, με ακριβώς αρκετή διαφορά για να μείνει ενδιαφέρον.', emoji: '🧲' },
  { id: 'score_7_result_08', score: 7, titleEn: 'A Genuinely Strong Sign', titleGr: 'Ένα Πραγματικά Δυνατό Σημάδι', descriptionEn: 'Seven matches is a genuinely strong sign of real compatibility between you two.', descriptionGr: 'Επτά ταιριάσματα είναι ένα πραγματικά δυνατό σημάδι γνήσιας συμβατότητας μεταξύ σας.', emoji: '💪' },
  { id: 'score_7_result_09', score: 7, titleEn: 'More Alike Than You\'d Expect', titleGr: 'Πιο Όμοιοι από Ό,τι Θα Περίμενες', descriptionEn: 'You\'re more alike than most first conversations reveal — a solid sign worth exploring.', descriptionGr: 'Είστε πιο όμοιοι από ό,τι αποκαλύπτουν οι περισσότερες πρώτες συζητήσεις — ένα στέρεο σημάδι που αξίζει να εξερευνηθεί.', emoji: '🔮' },
  { id: 'score_7_result_10', score: 7, titleEn: 'Strong Ground to Build On', titleGr: 'Δυνατό Έδαφος για να Χτίσετε', descriptionEn: 'This is strong, genuine ground to keep building a real connection on.', descriptionGr: 'Αυτό είναι δυνατό, γνήσιο έδαφος για να συνεχίσετε να χτίζετε μια πραγματική σύνδεση.', emoji: '🏗️' },
  { id: 'score_8_result_01', score: 8, titleEn: 'A Very Strong Match', titleGr: 'Πολύ Δυνατό Ταίριασμα', descriptionEn: 'Eight out of ten matched — a very strong connection, with a few interesting differences to explore.', descriptionGr: 'Οκτώ στα δέκα ταίριαξαν — μια πολύ δυνατή σύνδεση, με μερικές ενδιαφέρουσες διαφορές να εξερευνήσετε.', emoji: '🔥' },
  { id: 'score_8_result_02', score: 8, titleEn: 'Deeply Aligned', titleGr: 'Βαθιά Ευθυγραμμισμένοι', descriptionEn: 'You\'re deeply aligned on almost everything, with just enough contrast to keep it exciting.', descriptionGr: 'Είστε βαθιά ευθυγραμμισμένοι σε σχεδόν όλα, με ακριβώς αρκετή αντίθεση για να μείνει συναρπαστικό.', emoji: '🌠' },
  { id: 'score_8_result_03', score: 8, titleEn: 'Rarely This Close', titleGr: 'Σπάνια Τόσο Κοντά', descriptionEn: 'It\'s rare to see this much alignment — a genuinely strong signal between you two.', descriptionGr: 'Είναι σπάνιο να δεις τόση ευθυγράμμιση — ένα πραγματικά δυνατό σήμα μεταξύ σας.', emoji: '💎' },
  { id: 'score_8_result_04', score: 8, titleEn: 'An Excellent Overlap', titleGr: 'Εξαιρετική Επικάλυψη', descriptionEn: 'Your overlap is excellent — eight genuine matches with a couple of interesting exceptions.', descriptionGr: 'Η επικάλυψή σας είναι εξαιρετική — οκτώ γνήσια ταιριάσματα με μερικές ενδιαφέρουσες εξαιρέσεις.', emoji: '🌟' },
  { id: 'score_8_result_05', score: 8, titleEn: 'A Strong Foundation, Confirmed', titleGr: 'Μια Δυνατή Βάση, Επιβεβαιωμένη', descriptionEn: 'This confirms a genuinely strong foundation — well beyond what most pairs land on.', descriptionGr: 'Αυτό επιβεβαιώνει μια πραγματικά δυνατή βάση — πολύ πέρα από ό,τι καταλήγουν οι περισσότεροι.', emoji: '🏆' },
  { id: 'score_8_result_06', score: 8, titleEn: 'Impressively Compatible', titleGr: 'Εντυπωσιακά Συμβατοί', descriptionEn: 'You\'re impressively compatible on most fronts — this is well worth paying attention to.', descriptionGr: 'Είστε εντυπωσιακά συμβατοί στα περισσότερα μέτωπα — αυτό αξίζει σίγουρα την προσοχή σας.', emoji: '🎊' },
  { id: 'score_8_result_07', score: 8, titleEn: 'Two Minds, Mostly Alike', titleGr: 'Δύο Μυαλά, Κυρίως Όμοια', descriptionEn: 'Two minds that think alike far more often than not — a genuinely strong pairing.', descriptionGr: 'Δύο μυαλά που σκέφτονται όμοια πολύ πιο συχνά παρά όχι — ένα πραγματικά δυνατό ζευγάρι.', emoji: '🧠' },
  { id: 'score_8_result_08', score: 8, titleEn: 'Close to the Top', titleGr: 'Κοντά στην Κορυφή', descriptionEn: 'You\'re close to the top of the scale — very strong alignment with a bit of healthy contrast.', descriptionGr: 'Είστε κοντά στην κορυφή της κλίμακας — πολύ δυνατή ευθυγράμμιση με λίγη υγιή αντίθεση.', emoji: '🏔️' },
  { id: 'score_8_result_09', score: 8, titleEn: 'A Confident Connection', titleGr: 'Μια Σίγουρη Σύνδεση', descriptionEn: 'Eight matches gives you real confidence that this connection has genuine substance.', descriptionGr: 'Οκτώ ταιριάσματα σας δίνουν πραγματική σιγουριά ότι αυτή η σύνδεση έχει γνήσια ουσία.', emoji: '🎗️' },
  { id: 'score_8_result_10', score: 8, titleEn: 'Strikingly in Sync', titleGr: 'Εντυπωσιακά σε Συγχρονισμό', descriptionEn: 'You\'re strikingly in sync — the small differences left only add character.', descriptionGr: 'Είστε εντυπωσιακά σε συγχρονισμό — οι μικρές διαφορές που απομένουν προσθέτουν μόνο χαρακτήρα.', emoji: '🎶' },
  { id: 'score_9_result_01', score: 9, titleEn: 'A Rare Connection', titleGr: 'Μια Σπάνια Σύνδεση', descriptionEn: 'Nine out of ten — a genuinely rare level of connection, with one small difference to keep things human.', descriptionGr: 'Εννέα στα δέκα — ένα πραγματικά σπάνιο επίπεδο σύνδεσης, με μία μικρή διαφορά που κρατά τα πράγματα ανθρώπινα.', emoji: '💎' },
  { id: 'score_9_result_02', score: 9, titleEn: 'Almost Perfectly Aligned', titleGr: 'Σχεδόν Τέλεια Ευθυγραμμισμένοι', descriptionEn: 'You\'re almost perfectly aligned — this level of similarity doesn\'t happen often.', descriptionGr: 'Είστε σχεδόν τέλεια ευθυγραμμισμένοι — αυτό το επίπεδο ομοιότητας δεν συμβαίνει συχνά.', emoji: '🌈' },
  { id: 'score_9_result_03', score: 9, titleEn: 'Exceptionally In Sync', titleGr: 'Εξαιρετικά σε Συγχρονισμό', descriptionEn: 'Nine genuine matches is exceptionally rare — you clearly see the world in a very similar way.', descriptionGr: 'Εννέα γνήσια ταιριάσματα είναι εξαιρετικά σπάνιο — προφανώς βλέπετε τον κόσμο με πολύ παρόμοιο τρόπο.', emoji: '🔗' },
  { id: 'score_9_result_04', score: 9, titleEn: 'A Remarkable Overlap', titleGr: 'Μια Αξιοσημείωτη Επικάλυψη', descriptionEn: 'This is a remarkable overlap — the kind that\'s genuinely uncommon between two people.', descriptionGr: 'Αυτή είναι μια αξιοσημείωτη επικάλυψη — το είδος που είναι πραγματικά ασυνήθιστο ανάμεσα σε δύο ανθρώπους.', emoji: '🌌' },
  { id: 'score_9_result_05', score: 9, titleEn: 'One Difference, Much in Common', titleGr: 'Μία Διαφορά, Πολλά Κοινά', descriptionEn: 'Just one thing set you apart — everything else lined up in a genuinely rare way.', descriptionGr: 'Μόνο ένα πράγμα σας ξεχώρισε — όλα τα υπόλοιπα ταίριαξαν με έναν πραγματικά σπάνιο τρόπο.', emoji: '🧿' },
  { id: 'score_9_result_06', score: 9, titleEn: 'Strikingly Similar', titleGr: 'Εντυπωσιακά Όμοιοι', descriptionEn: 'You\'re strikingly similar in how you see things — this kind of alignment stands out.', descriptionGr: 'Είστε εντυπωσιακά όμοιοι στο πώς βλέπετε τα πράγματα — αυτό το είδος ευθυγράμμισης ξεχωρίζει.', emoji: '🪞' },
  { id: 'score_9_result_07', score: 9, titleEn: 'A Near-Perfect Fit', titleGr: 'Σχεδόν Τέλειο Ταίριασμα', descriptionEn: 'This is about as close to a perfect fit as it gets, with one small human wrinkle left.', descriptionGr: 'Αυτό είναι σχεδόν τέλειο ταίριασμα, με μία μικρή ανθρώπινη λεπτομέρεια που απομένει.', emoji: '🧷' },
  { id: 'score_9_result_08', score: 9, titleEn: 'Uncommonly Compatible', titleGr: 'Ασυνήθιστα Συμβατοί', descriptionEn: 'You\'re uncommonly compatible — this level of shared perspective is genuinely special.', descriptionGr: 'Είστε ασυνήθιστα συμβατοί — αυτό το επίπεδο κοινής οπτικής είναι πραγματικά ξεχωριστό.', emoji: '🦋' },
  { id: 'score_9_result_09', score: 9, titleEn: 'So Close to Everything', titleGr: 'Τόσο Κοντά σε Όλα', descriptionEn: 'You matched on almost everything — a genuinely exceptional result worth noticing.', descriptionGr: 'Ταιριάξατε σχεδόν σε όλα — ένα πραγματικά εξαιρετικό αποτέλεσμα που αξίζει προσοχή.', emoji: '🌠' },
  { id: 'score_9_result_10', score: 9, titleEn: 'A Standout Result', titleGr: 'Ένα Ξεχωριστό Αποτέλεσμα', descriptionEn: 'Nine matches is a standout result — the kind that doesn\'t come around often.', descriptionGr: 'Εννέα ταιριάσματα είναι ένα ξεχωριστό αποτέλεσμα — το είδος που δεν συμβαίνει συχνά.', emoji: '🏵️' },
  { id: 'score_10_result_01', score: 10, titleEn: 'A Perfect Score', titleGr: 'Τέλειο Σκορ', descriptionEn: 'Ten out of ten — an exceptional alignment on paper. What happens next is still up to the two of you.', descriptionGr: 'Δέκα στα δέκα — μια εξαιρετική ευθυγράμμιση στα χαρτιά. Το τι θα συμβεί μετά εξαρτάται ακόμα από εσάς τους δύο.', emoji: '🏆' },
  { id: 'score_10_result_02', score: 10, titleEn: 'Exceptionally Aligned', titleGr: 'Εξαιρετικά Ευθυγραμμισμένοι', descriptionEn: 'Every single answer lined up — a genuinely exceptional result. Enjoy discovering what\'s behind it.', descriptionGr: 'Κάθε απάντηση ταίριαξε — ένα πραγματικά εξαιρετικό αποτέλεσμα. Απολαύστε την ανακάλυψη του τι κρύβεται πίσω από αυτό.', emoji: '🌟' },
  { id: 'score_10_result_03', score: 10, titleEn: 'A Rare Full House', titleGr: 'Ένα Σπάνιο Γεμάτο Χέρι', descriptionEn: 'A perfect ten is rare — it says a lot about how alike you are, without saying everything.', descriptionGr: 'Ένα τέλειο δέκα είναι σπάνιο — λέει πολλά για το πόσο όμοιοι είστε, χωρίς να λέει τα πάντα.', emoji: '🃏' },
  { id: 'score_10_result_04', score: 10, titleEn: 'Off the Charts', titleGr: 'Εκτός Κλίμακας', descriptionEn: 'This score is off the charts — a fantastic sign, and a great excuse to keep talking.', descriptionGr: 'Αυτό το σκορ είναι εκτός κλίμακας — ένα φανταστικό σημάδι, και μια εξαιρετική αφορμή να συνεχίσετε να μιλάτε.', emoji: '📊' },
  { id: 'score_10_result_05', score: 10, titleEn: 'A Flawless Round', titleGr: 'Ένας Άψογος Γύρος', descriptionEn: 'A flawless round of matches — impressive on every level, and worth celebrating.', descriptionGr: 'Ένας άψογος γύρος ταιριασμάτων — εντυπωσιακό σε κάθε επίπεδο, και αξίζει να το γιορτάσετε.', emoji: '🎉' },
  { id: 'score_10_result_06', score: 10, titleEn: 'Ten for Ten', titleGr: 'Δέκα στα Δέκα', descriptionEn: 'Ten for ten — this is as strong an alignment as this game can show you.', descriptionGr: 'Δέκα στα δέκα — αυτή είναι η πιο δυνατή ευθυγράμμιση που μπορεί να σας δείξει αυτό το παιχνίδι.', emoji: '🔟' },
  { id: 'score_10_result_07', score: 10, titleEn: 'A Remarkable Alignment', titleGr: 'Μια Αξιοσημείωτη Ευθυγράμμιση', descriptionEn: 'A remarkable, complete alignment — the perfect spark for a real first conversation.', descriptionGr: 'Μια αξιοσημείωτη, πλήρης ευθυγράμμιση — η τέλεια σπίθα για μια πραγματική πρώτη συζήτηση.', emoji: '⭐' },
  { id: 'score_10_result_08', score: 10, titleEn: 'Everything Lined Up', titleGr: 'Όλα Ταίριαξαν', descriptionEn: 'Everything lined up this round — a genuinely exciting result to build a real connection on.', descriptionGr: 'Όλα ταίριαξαν αυτόν τον γύρο — ένα πραγματικά συναρπαστικό αποτέλεσμα για να χτίσετε μια πραγματική σύνδεση.', emoji: '💯' },
  { id: 'score_10_result_09', score: 10, titleEn: 'A Genuine Ten', titleGr: 'Ένα Γνήσιο Δέκα', descriptionEn: 'A genuine, complete ten — impressive, exciting, and a great reason to keep the conversation going.', descriptionGr: 'Ένα γνήσιο, πλήρες δέκα — εντυπωσιακό, συναρπαστικό, και μια εξαιρετική αφορμή να συνεχίσετε τη συζήτηση.', emoji: '🎇' },
  { id: 'score_10_result_10', score: 10, titleEn: 'As Good As It Gets', titleGr: 'Όσο Καλύτερα Γίνεται', descriptionEn: 'As good as this game can show — now it\'s up to real conversation to see where it goes.', descriptionGr: 'Όσο καλύτερα μπορεί να δείξει αυτό το παιχνίδι — τώρα εξαρτάται από την πραγματική συζήτηση το πού θα πάει.', emoji: '🥇' },
]


// All variations for a given real match count (0-10).
export function getResultPool(score: number): MysteryResultVariation[] {
  const clamped = Math.max(0, Math.min(10, Math.round(score)))
  return MYSTERY_RESULT_LIBRARY.filter(r => r.score === clamped)
}

// Pick one variation at random from the correct score's pool. Callers are
// responsible for calling this exactly once per completed game and saving
// the returned id into shared state — this function itself has no memory
// of previous selections, so calling it again (e.g. on Play Again, which
// starts a brand-new session) can naturally produce a different result
// even for the same score.
export function selectRandomResult(score: number): MysteryResultVariation {
  const pool = getResultPool(score)
  const fallbackPool = pool.length > 0 ? pool : MYSTERY_RESULT_LIBRARY.filter(r => r.score === 5)
  const index = Math.floor(Math.random() * fallbackPool.length)
  return fallbackPool[index]
}

// Look up a previously-selected result by its saved id (used when rendering
// a completed game — both players and a page refresh resolve the same id).
export function getResultById(id: string): MysteryResultVariation | null {
  return MYSTERY_RESULT_LIBRARY.find(r => r.id === id) || null
}
